include:
- masto-src.tar.gz
kind: ArchiveUploadSpec
name: masto-src-tar-gz-y8OW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: masto-test-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://masto-src-tar-gz-y8OW
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-10T14:00:34Z"
