# config/es-env.yaml

singleuser:
  extraEnv:
    ES_HOST: "https://elasticsearch-master.elastic.svc.cluster.local:9200"

# get from secret
hub:
  config:
    KubeSpawner:
      env:
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: es-credentials
              key: username
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: es-credentials
              key: password

