---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-git-demo
  namespace: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-git-demo
  template:
    metadata:
      labels:
        app: notebook-git-demo
    spec:
      volumes:
        - name: workspace
          emptyDir: {}
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.2.2
          env:
            - name: GIT_SYNC_REPO
              value: "https://gitlab.unimelb.edu.au/ygao3631/comp_team_43.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_ONE_TIME
              value: "false"
            - name: GIT_SYNC_WAIT
              value: "30"
            - name: GIT_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gitlab-credentials
                  key: username
            - name: GIT_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-credentials
                  key: password
          volumeMounts:
            - name: workspace
              mountPath: /git
        - name: notebook
          image: jupyter/base-notebook:latest
          command:
            - start-notebook.sh
            - "--NotebookApp.token=comp_team_43"
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: workspace
              mountPath: /home/jovyan/work
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-git-demo
  namespace: notebook
spec:
  selector:
    app: notebook-git-demo
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notebook-git-demo
  namespace: notebook
  annotations:
    # 开启正则支持
    nginx.ingress.kubernetes.io/use-regex: "true"
    # 将 /demo/<whatever> 重写为 /<whatever>
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: jupyter.elec-analysis.com
      http:
        paths:
          - path: /demo(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notebook-git-demo
                port:
                  number: 8888

